[pytest]
addopts = --alluredir=allure-results -q
markers =
    smoke: Quick smoke tests
    regression: Full regression suite
testpaths = testcases
python_files = test_*.py
filterwarnings =ignore::pytest.PytestUnraisableExceptionWarning