uname_field_id = "edit-name"
pwd_field_id = "edit-pass"
submit_btn_id = "edit-submit"
reason_field_id = "reason_textbox"
payer_selector_id = "qt-filter-label"
user_icon_xpath = "//*[@data-target='user_menu_dropdown']"
logout_btn_xpath = "// *[ @class ='not_for_mobile logout_msg']"
globalsearchbar_id = "globalsearch_input"
searchresult_id = "search_results"
pencil_icon_xpath = "//*[@class='pencil_icon right mrm']//*[@class='addSuppData-trigger pts']"
dasboard_xpath = "//*[@class='poc_dashboard pbb']"
confirm_disconfirm_xpath = "//*[contains(text(),'Confirm/Disconfirm')]"
pre_review_xpath = "//*[contains(text(),'Pre-review Report')]"
poc_body_xpath = "//*[@class='poc_body']"
recapture_tag_xpath = "//span[contains(text(),'Recapture')]"
suspect_tag_xpath = "//span[contains(text(),'Suspect')]"
confirm_tooltip_xpath = ""
disconfirm_tooltip_xpath = ""
not_addressed_tooltip_xpath = ""
add_dx_btn_xpath = "" 
add_dx_modal_id = "review_dx_input"
add_dx_modal_list_id = "ac-dropdown-review_dx_input"
add_note_xpath = ""
note_text_id = "edit-note-field"
note_save_btn_xpath = "//a[contains(text(),'Save')]"
note_suggestions_list_xpath = "//ul[@id='ac-dropdown-edit-note-field']"
dos_field_id = "enc_service_date"
provider_field_xpath = "//input[@id='provider_name']"
provider_list_xpath = "//ul[@id='ac-dropdown-provider_name']"
poc_save_draft_btn_id = "save_draft"
poc_submit_btn_id = "poc_submit"
poc_delete_btn_id = "delete_task"
drupal_alert_class_xpath = "//*[@class='drupal_message_text']"
autosave_id = "last_draft_time"
delete_reason_input_xpath = "//*[contains(text(),'Are you sure you want to delete this task?')]/..//*[@class='input-field']"
delete_modal_btn_xpath = "//*[contains(text(),'Delete')]"